--- 

- name: Create api-edge-service directory
  file:
    path: "{{ item }}"
    state: directory
    owner: nobody
    group: root
    mode: 0775
  with_items:
    - /srv/api_web_demo
  become: yes
  tags: 
    - create_web

- name: Copy code api 
  copy: >
    src=../../../../api/{{ item }}
    dest=/srv/api_web_demo/
    mode=0755
  with_items:
    - logs 
    - nginxconf 
    - rabbitmq 
    - route 
    - static 
    - templates 
    - __init__.py 
    - config.py 
    - crud.py 
    - database.py 
    - main.py 
    - models.py 
    - redis_connecttion.py 
    - requirements.txt 
    - schemas.py 
    - utils.py
  become: yes
  tags: 
    - create_web
    - update_code

- name: Sync database
  copy: >
    src=../../../../api/{{ item }}
    dest=/srv/api_web_demo/database/
    mode=0755
  with_items:
      - database_domain.db 
  become: yes
  tags: 
    - create_web
    - update_database

- name: Initiate virtualenv
  shell:
    cmd: python3 -m venv venv
    chdir: /srv/api_web_demo
  become: yes
  tags: 
    - create_web
    - create_env

- name: Upgrade pips
  shell:
    cmd: sudo /srv/api_web_demo/venv/bin/pip install --upgrade pip
    chdir: /srv/api_web_demo/
  become: yes
  tags: 
    - create_web

- name: Install packet
  shell:
    cmd: sudo /srv/api_web_demo/venv/bin/pip install -r requirements.txt
    chdir: /srv/api_web_demo/
  tags: 
    - create_web
    - update_code

- name: Copy file supervisor config
  template: >
    src=../files/{{ item }}
    dest=/etc/supervisor/conf.d/
  with_items:
    - api_web_demo.conf
  become: yes
  tags: 
    - create_web
    - update_code

- name: Restart process
  supervisorctl:
    name: api_web_demo
    state: restarted
  become: yes
  tags: 
    - create_web
    - update_code
